import { useState, useRef, useEffect } from 'react'
import { Download, Printer, Bot, Send, Edit3, Type, List, AlignLeft, RefreshCw } from 'lucide-react'
import { useAuth } from '../../contexts/AuthContext'
import api from '../../services/api/auth'

const AuditorReports = () => {
  const { user } = useAuth()
  const [isGenerating, setIsGenerating] = useState(false)

  const [aiInput, setAiInput] = useState('')
  const [chatMessages, setChatMessages] = useState<{role: 'ai' | 'user', text: string}[]>([
    { role: 'ai', text: 'I can help you modify this report. Ask me to add specific data, format sections, or summarize findings.' }
  ])
  const [isAiTyping, setIsAiTyping] = useState(false)
  const editorRef = useRef<HTMLDivElement>(null)

  const generateInitialReport = () => {
    setIsGenerating(true)
    setTimeout(() => {
      const initialHTML = `
        <h1 class="text-3xl font-bold text-slate-800 mb-6">Audit Exception Report: FY2026-Q1</h1>
        <div class="mb-4 text-sm text-slate-500">
          <p><strong>Generated By:</strong> ${user?.firstName || 'Lead Auditor'}</p>
          <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
          <p><strong>System Status:</strong> <span class="text-teal-600 font-semibold">Continuous Monitoring Active</span></p>
        </div>
        
        <hr class="my-6 border-slate-300" />
        
        <h2 class="text-xl font-bold text-slate-700 mt-8 mb-4">1. Executive Summary</h2>
        <p class="text-slate-600 mb-4 leading-relaxed">
          The continuous AI monitoring system analyzed 14,204 transactions in the current period. The overall risk index remains within an acceptable threshold, but two critical anomalies require immediate investigation. 
        </p>

        <h2 class="text-xl font-bold text-slate-700 mt-8 mb-4">2. High-Risk Findings (Active Flags)</h2>
        
        <div class="bg-red-50 border-l-4 border-red-500 p-4 mb-6 mt-4">
          <h3 class="text-red-700 font-bold mb-2">Flag #1: Split Billing / Invoice Duplication (Risk Score: 94)</h3>
          <p class="text-slate-700 text-sm mb-2"><strong>Transaction ID:</strong> TRX-10492</p>
          <p class="text-slate-700 text-sm mb-2"><strong>Reason:</strong> Transaction processed at 2:00 AM on Sunday, matching an identical amount from vendor V-001 within 48 hours.</p>
          <p class="text-slate-700 text-sm"><strong>Required Action:</strong> Freeze vendor account. Request manual voucher review from Department Head.</p>
        </div>

        <div class="bg-amber-50 border-l-4 border-amber-500 p-4 mb-6">
          <h3 class="text-amber-700 font-bold mb-2">Flag #2: Budget Variance / New Vendor (Risk Score: 65)</h3>
          <p class="text-slate-700 text-sm mb-2"><strong>Transaction ID:</strong> TRX-10501</p>
          <p class="text-slate-700 text-sm mb-2"><strong>Reason:</strong> First-time payment to vendor V-099 exceeds typical departmental budget threshold by 45%.</p>
          <p class="text-slate-700 text-sm"><strong>Required Action:</strong> Verify vendor in Master Data. Request budget amendment authorization.</p>
        </div>

        <h2 class="text-xl font-bold text-slate-700 mt-8 mb-4">3. Next Steps & Recommendations</h2>
        <ul class="list-disc pl-6 text-slate-600 mb-6 space-y-2">
          <li>Immediate meeting with Procurement to review Vendor V-001 mapping.</li>
          <li>Update rule constraints for offshore weekend processing.</li>
          <li>Approve closure of Flag #2 upon receipt of budget authorization.</li>
        </ul>
      `
      if (editorRef.current) {
        editorRef.current.innerHTML = initialHTML
      }
      setIsGenerating(false)
    }, 1500)
  }

  // Generate report on initial load
  useEffect(() => {
    generateInitialReport()
  }, [])

  const handleEditorInput = (e: React.FormEvent<HTMLDivElement>) => {
    // Keep internal state synched if needed globally later
    e.preventDefault()
  }

  const handleAiSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!aiInput.trim()) return

    setChatMessages(prev => [...prev, { role: 'user', text: aiInput }])
    const promptBackup = aiInput
    setAiInput('')
    setIsAiTyping(true)

    // Simulate AI modifying the report
    const fetchAiEdit = async () => {
      try {
        const response = await api.post('/reports/edit', {
          html: editorRef.current?.innerHTML || "",
          prompt: promptBackup
        })
        
        if (response.data) {
          if (editorRef.current) {
            editorRef.current.innerHTML = response.data.html
          }
          setChatMessages(prev => [...prev, { role: 'ai', text: response.data.message }])
        }
      } catch (err) {
        console.error(err)
        setTimeout(() => {
          let aiResponseText = ""
          const currentInputLower = promptBackup.toLowerCase()
          if (currentInputLower.includes("add") || currentInputLower.includes("append")) {
            aiResponseText = "Offline Mode: Content simulated."
            if (editorRef.current) {
              const currentHTML = editorRef.current.innerHTML
              const newHTML = currentHTML.replace(
                'require immediate investigation.', 
                `require immediate investigation. <span class="bg-teal-100 text-teal-800 px-1 rounded">Additionally, the AI model has noted a 12% increase in late payments.</span>`
              )
              editorRef.current.innerHTML = newHTML
            }
          } else {
            aiResponseText = "Offline Mode: Backend unreachable."
          }
          setChatMessages(prev => [...prev, { role: 'ai', text: aiResponseText }])
          setIsAiTyping(false)
        }, 1500)
      } finally {
        setIsAiTyping(false)
      }
    }
    fetchAiEdit()
  }

  const execCommand = (command: string) => {
    document.execCommand(command, false)
  }

  return (
    <div className="flex h-full bg-slate-900 border-l border-slate-800">
      
      {/* Main Report Editor Area */}
      <div className="flex-1 flex flex-col relative bg-slate-100 overflow-hidden rounded-tl-3xl shadow-[-10px_0_30px_rgba(0,0,0,0.5)] z-10">
        
        {/* Editor Toolbar */}
        <div className="h-16 px-6 border-b border-slate-300 flex items-center justify-between bg-white sticky top-0 z-20 shadow-sm">
          <div className="flex items-center gap-2">
            <div className="flex bg-slate-100 rounded-lg p-1 border border-slate-200">
              <button onClick={() => execCommand('bold')} className="p-2 text-slate-600 hover:text-slate-900 hover:bg-slate-200 rounded transition-colors" title="Bold"><Type className="w-4 h-4 font-bold" /></button>
              <button onClick={() => execCommand('italic')} className="p-2 text-slate-600 hover:text-slate-900 hover:bg-slate-200 rounded transition-colors italic" title="Italic"><Type className="w-4 h-4" /></button>
              <button onClick={() => execCommand('underline')} className="p-2 text-slate-600 hover:text-slate-900 hover:bg-slate-200 rounded transition-colors underline" title="Underline"><Type className="w-4 h-4" /></button>
            </div>
            <div className="w-px h-6 bg-slate-300 mx-2"></div>
            <div className="flex bg-slate-100 rounded-lg p-1 border border-slate-200">
              <button onClick={() => execCommand('insertUnorderedList')} className="p-2 text-slate-600 hover:text-slate-900 hover:bg-slate-200 rounded transition-colors" title="Bullet List"><List className="w-4 h-4" /></button>
              <button onClick={() => execCommand('justifyLeft')} className="p-2 text-slate-600 hover:text-slate-900 hover:bg-slate-200 rounded transition-colors" title="Align Left"><AlignLeft className="w-4 h-4" /></button>
            </div>
          </div>
          
          <div className="flex items-center gap-3">
            <button 
              onClick={generateInitialReport}
              className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-slate-600 hover:text-slate-900 bg-slate-100 hover:bg-slate-200 rounded-md border border-slate-300 transition-colors"
            >
              <RefreshCw className={`w-4 h-4 ${isGenerating ? 'animate-spin' : ''}`} />
              Refresh Data
            </button>
            <button 
              onClick={() => window.print()}
              className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-white bg-slate-800 hover:bg-slate-700 rounded-md transition-colors shadow-sm"
            >
              <Printer className="w-4 h-4" />
              Print
            </button>
            <button 
              onClick={() => window.print()} 
              className="flex items-center gap-2 px-4 py-1.5 text-sm font-medium text-white bg-teal-600 hover:bg-teal-500 rounded-md transition-colors shadow-md shadow-teal-500/20"
            >
              <Download className="w-4 h-4" />
              Export PDF
            </button>
          </div>
        </div>

        {/* Paper Document Area */}
        <div className="flex-1 overflow-y-auto p-8 lg:p-12 scroll-smooth bg-slate-100 print:p-0 print:bg-white">
          
          {isGenerating && (
            <div className="max-w-[850px] min-h-[1056px] mx-auto bg-white shadow-xl flex items-center justify-center border border-slate-200 print:hidden">
              <div className="text-center">
                <div className="w-12 h-12 border-4 border-slate-200 border-t-teal-600 rounded-full animate-spin mx-auto mb-4"></div>
                <h3 className="text-lg font-bold text-slate-700">Compiling Report Data...</h3>
                <p className="text-slate-500 text-sm">Fetching live flags and running NLP summarization</p>
              </div>
            </div>
          )}
          
          <div className={`max-w-[850px] mx-auto relative group ${isGenerating ? 'hidden' : 'block'}`}>
            <div className="absolute -left-12 top-0 opacity-0 group-hover:opacity-100 transition-opacity flex flex-col gap-2 print:hidden">
              <div className="p-2 bg-slate-800 text-white rounded-lg shadow-lg cursor-pointer hover:bg-slate-700" title="Edit Mode Active">
                <Edit3 className="w-5 h-5" />
              </div>
            </div>

            {/* Editable WYSIWYG Content */}
            <div 
              ref={editorRef}
              contentEditable 
              onInput={handleEditorInput}
              className="min-h-[1056px] bg-white shadow-xl p-12 lg:p-16 border border-slate-200 focus:outline-none focus:ring-2 focus:ring-teal-500 focus:border-transparent prose prose-slate max-w-none print:shadow-none print:border-none print:p-0"
              style={{
                fontFamily: '"Times New Roman", Times, serif'
              }}
            />
          </div>
        </div>
      </div>

      {/* Right Sidebar - AI Copilot for Report */}
      <div className="w-96 flex flex-col bg-slate-900 border-l border-slate-800 shrink-0">
        <div className="h-16 px-6 border-b border-slate-800 flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-teal-500/20 flex items-center justify-center border border-teal-500/30">
            <Bot className="w-4 h-4 text-teal-400" />
          </div>
          <h2 className="text-white font-semibold">Report Editor AI</h2>
        </div>
        
        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          {chatMessages.map((msg, idx) => (
            <div key={idx} className={`flex gap-3 ${msg.role === 'user' ? 'flex-row-reverse' : ''} animate-fade-in`}>
              <div className={`w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 ${
                msg.role === 'user' ? 'bg-slate-700 text-slate-300' : 'bg-teal-500/20 border border-teal-500/30 text-teal-400'
              }`}>
                {msg.role === 'user' ? <Type className="w-4 h-4" /> : <Bot className="w-4 h-4" />}
              </div>
              <div className={`p-3 rounded-xl text-sm leading-relaxed max-w-[80%] ${
                msg.role === 'user' 
                  ? 'bg-slate-800 text-slate-200' 
                  : 'bg-slate-800/50 border border-slate-700 text-slate-300'
              }`}>
                {msg.text}
              </div>
            </div>
          ))}
          
          {isAiTyping && (
            <div className="flex gap-3 animate-fade-in">
              <div className="w-8 h-8 rounded-lg bg-teal-500/20 border border-teal-500/30 flex items-center justify-center text-teal-400">
                <Bot className="w-4 h-4" />
              </div>
              <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-3 flex items-center gap-1.5 max-w-[80%]">
                <div className="w-1.5 h-1.5 bg-teal-500 rounded-full animate-bounce"></div>
                <div className="w-1.5 h-1.5 bg-teal-500 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
                <div className="w-1.5 h-1.5 bg-teal-500 rounded-full animate-bounce" style={{ animationDelay: '0.4s' }}></div>
              </div>
            </div>
          )}
        </div>

        <div className="p-4 bg-slate-900 border-t border-slate-800">
          <div className="mb-3 flex flex-wrap gap-2">
            <button onClick={() => setAiInput("Format the flag section as a table")} className="text-[10px] px-2 py-1 bg-slate-800 hover:bg-slate-700 text-slate-400 rounded-md border border-slate-700 transition-colors">
              Format to table
            </button>
            <button onClick={() => setAiInput("Add a paragraph detailing the IT sector late payments")} className="text-[10px] px-2 py-1 bg-slate-800 hover:bg-slate-700 text-slate-400 rounded-md border border-slate-700 transition-colors">
              Add IT Sector data
            </button>
          </div>
          <form onSubmit={handleAiSubmit} className="relative">
            <input
              type="text"
              value={aiInput}
              onChange={(e) => setAiInput(e.target.value)}
              placeholder="Ask AI to modify the report..."
              className="w-full bg-slate-800 border border-slate-700 text-white rounded-xl pl-4 pr-10 py-3 text-sm focus:outline-none focus:border-teal-500/50 transition-colors"
            />
            <button 
              type="submit"
              disabled={!aiInput.trim() || isAiTyping || isGenerating}
              className={`absolute right-2 top-2 bottom-2 rounded-lg aspect-square flex items-center justify-center transition-colors ${
                aiInput.trim() && !isAiTyping && !isGenerating
                  ? 'bg-teal-500 hover:bg-teal-400 text-white' 
                  : 'text-slate-500 cursor-not-allowed'
              }`}
            >
              <Send className="w-4 h-4 mr-0.5 mt-0.5" />
            </button>
          </form>
        </div>
      </div>

    </div>
  )
}

export default AuditorReports
